### ISSUE TITLE
themes 附加css 优化

### ISSUE THREAD

**Issue by StringKe** [b3log/pipe-themes#1]
# Medium
```css
.post__title {
    text-align: center;   /*add*/
    text-shadow: 3px 2px 0px rgb(234, 234, 234);   /*add*/
}
.article__item{
    border-radius: 3px;
}
.article__item--big .article__thumb{
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}
```
![image](https://user-images.githubusercontent.com/31089228/37012917-082d6fe6-2132-11e8-9a4f-c589b12f126f.png)

在文章过段的情况下sidbar会影响美观 隔开一点或者浮动 应该会比较好看
.article__comment 的width应保持与 .wrapper 宽度一致
文章页面顶部的搜索应与右侧头像对齐

文章单页设计应保持 主体部分宽度一致  强迫症很难受
![image](https://user-images.githubusercontent.com/31089228/37013093-06c828b6-2133-11e8-9e62-5b8af05c0f2c.png)

## 滚动条优化
```css
body::-webkit-scrollbar {
    width: 7px;
}
body::-webkit-scrollbar-thumb {
    background-color: #cacaca;
    border-radius: 3px;
}
body::-webkit-scrollbar-track {
    background-color: #fbf7f7;
}
::selection {
    text-shadow: none;
    background: rgba(35, 67, 119, 0.4);
}
```
